version: "3.3"
services:
  delta:
    depends_on:
      - keycloak
      - elasticsearch
      - cassandra
      - blazegraph
      - storage-service
    image: bluebrain/nexus-delta:1.4.1
    entrypoint: ["bin/wait-for-it.sh", "-s", "-t", "0", "cassandra:9042", "--", "./bin/delta",
                 "-Xmx2G",
                 "-Dapp.instance.interface=0.0.0.0",
                 "-Dapp.http.interface=0.0.0.0",
                 "-Dapp.http.public-uri=https://test.nexus.bbp.epfl.ch",
                 "-Dapp.service-account-caller.realm=internal",
                 "-Dapp.service-account-caller.subject=service-account-delta",
                 "-Dapp.service-account-caller.groups.1=delta",
                 "-Dapp.elastic-search.base=http://elasticsearch:9200",
                 "-Dapp.sparql.base=http://blazegraph:9999/blazegraph",
                 "-Dapp.storage.remote-disk.default-endpoint=http://storage-service:8080",
                 "-Dakka.persistence.cassandra.journal.keyspace-autocreate=true",
                 "-Dakka.persistence.cassandra.journal.tables-autocreate=true",
                 "-Dakka.persistence.cassandra.snapshot.keyspace-autocreate=true",
                 "-Dakka.persistence.cassandra.snapshot.tables-autocreate=true",
                 "-Dakka.persistence.cassandra.events-by-tag.pubsub-notification=true",
                 "-Ddatastax-java-driver.basic.contact-points.1=cassandra:9042",
                 "-Dkamon.modules.prometheus-reporter.enabled=false",
                 "-Dkamon.modules.jaeger.enabled=false"]
    ports:
      - "8080"

  storage-service:
    image: bluebrain/nexus-storage:1.4.1
    entrypoint: ["./bin/storage",
                 "-Dapp.instance.interface=0.0.0.0",
                 "-Dapp.http.interface=0.0.0.0",
                 "-Dapp.http.public-uri=http://storage.tests.nexus.ocp.bbp.epfl.ch",
                 "-Dapp.subject.anonymous=false",
                 "-Dapp.subject.realm=internal",
                 "-Dapp.subject.name=service-account-delta",
                 "-Dapp.storage.root-volume=/tmp",
                 "-Dapp.storage.fixer-enabled=false",
                 "-Dapp.delta.public-iri=https://test.nexus.bbp.epfl.ch",
                 "-Dapp.delta.internal-iri=http://delta:8080",
                 "-Dkamon.modules.prometheus-reporter.enabled=false",
                 "-Dkamon.modules.jaeger.enabled=false"]
    ports:
      - "8080"

  keycloak:
    image: "jboss/keycloak:11.0.1"
    environment:
      KEYCLOAK_USER: "admin"
      KEYCLOAK_PASSWORD: "admin"
      KEYCLOAK_FRONTEND_URL: "http://keycloak:8080/auth"
    ports:
      - "8080"

  elasticsearch:
    image: "docker.elastic.co/elasticsearch/elasticsearch:7.5.1"
    environment:
      ES_JAVA_OPTS: "-Xmx2G"
      discovery.type: "single-node"
      bootstrap.memory_lock: "true"

  cassandra:
    image: "cassandra:3.11.6"
    environment:
      JVM_OPTS: "-Xms1g -Xmx1g -Dcassandra.initial_token=0 -Dcassandra.skip_wait_for_gossip_to_settle=0"
      MAX_HEAP_SIZE: "1G"
      HEAP_NEWSIZE: "100m"
      CASSANDRA_BROADCAST_ADDRESS: cassandra
  blazegraph:
    image: bluebrain/blazegraph-nexus:2.1.5