prefix nsg: <https://bbp-nexus.epfl.ch/vocabs/bbp/neurosciencegraph/core/v0.1.0/>
prefix prov: <http://www.w3.org/ns/prov#>

select ?s where {
  ?s nsg:species <http://purl.obolibrary.org/obo/NCBITaxon_10116>

}
LIMIT 1000