export ANONYMOUS=true
export KG_BASE="http://192.168.159.10/v1"
export ADMIN_BASE=$KG_BASE

export NUM_PROJECTS=10
export PROJECT_NUMBER=1
export UPDATE_PROJECT=1
export UPDATE_REVISIONS=100
export UPDATE_REVISIONS_STEPS=1
export ATTACHMENT_INSTANCES=5000
export ATTACHMENTS_PER_INSTANCE=5
export ATTACHMENT_FETCH_DURATION="5 minutes"
export FETCH_DURATION="10 minutes"
export FETCH_PROJECT=1
export PARALLEL_USERS=96
export FETCH_USERS=$PARALLEL_USERS
export UPLOAD_SIZE=1000000

export FETCH_PERCENTAGE=40
export FETCH_AND_UPDATE_PERCENTAGE=20
export FETCH_AND_GET_BY_REVISION_PERCENTAGE=20
export BLAZEGRAPH_SEARCH_PERCENTAGE=3
export ES_SEARCH_PERCENTAGE=17
export MAX_RESOURCES=100000

